# Generated by Django 5.2.6 on 2025-09-21 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
