# Generated by Django 5.2.6 on 2025-09-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(default='Once upon a time...'),
        ),
    ]
